name: Build and Deploy Vue to Docker

on:
  push:
    branches:
      - hostinger_master
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - hostinger_master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU (for multi-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64  # Ensures it's built for AMD64
          tags: |
            ngjingchong/admin-portal:amd64
            ngjingchong/admin-portal:${{ github.sha }}
          cache-from: type=registry,ref=ngjingchong/admin-portal:amd64
          cache-to: type=inline

      - name: Verify the built image
        run: docker manifest inspect ngjingchong/admin-portal:amd64
