name: Build and Deploy Vue to Docker

on:
  push:
    branches:
      - ssl_config_0215
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - ssl_config_0215

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU (for multi-arch builds)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64  # Ensures it's built for AMD64
          tags: |
            ngjingchong/dev-admin-portal:amd64
            ngjingchong/dev-admin-portal:${{ github.sha }}
          cache-from: type=registry,ref=ngjingchong/dev-admin-portal:amd64
          cache-to: type=inline

      - name: Verify the built image
        run: docker manifest inspect ngjingchong/dev-admin-portal:amd64

      - name: Deploy to Hostinger VPS
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.VPS_SSH_PASSPHRASE }}
          script: |
            docker pull ngjingchong/dev-admin-portal:amd64
            docker stop dev-admin-portal || true
            docker rm dev-admin-portal || true
            docker rmi $(docker images -f "dangling=true" -q) || true
            docker run -d -p 8085:8085 --name dev-admin-portal --network application_network \
            -v /etc/nginx/conf.d/admin-portal.conf:/etc/nginx/conf.d/default.conf \
            ngjingchong/dev-admin-portal:amd64
